### ISSUE TITLE
Comparison to C string doesn't compile with VC 2010

### ISSUE THREAD

**Issue by ikolev21** [martinmoene/string-view-lite#28]
This doesn't compile with VC 2010:
```
string_view s;
s == "";
```
Need to write `s == string_view("");`

This looks like a problem of the compiler that's probably hard to work around.

**Comment by martinmoene** [comment]
[Such a comparison](https://github.com/martinmoene/string-view-lite/blob/e62738c387dcf3f563299c01c1a73b3d42e05587/test/string-view.t.cpp#L1012) is part of the tests and passes, so it's likely due to something else.

did you use `using namespace nonstd` or try
```
#include "nonstd/string_view.hpp"

void test()
{
    nonstd::string_view s;
    s == "";
}
```
Otherwise can you provide a [minimal 'nonworking' example](https://en.wikipedia.org/wiki/Minimal_working_example), including compilation command and relevant error message?

**Comment by ikolev21** [comment]
Sorry about the false alarm. This was caused by VS failing to rebuild the project properly.
The thing is that it is set up to compile with VC 2017 for x64 and with VC 2010 for Win32. For some reason (stale pre-compiled header?) the VC 2010 compilation had invalid value for `nssv_COMPILER_MSVC_VERSION` and tried to compile the C++11 branch of the #if's.

**Comment by martinmoene** [comment]
Thanks for your explanation :)
